### ISSUE TITLE
Batch processing for audio signals

### ISSUE THREAD

**Issue by saquibntt** [Sehaba95/Emotions-recognition-from-audio-signal#2]
Hi,

Thanks for sharing your results. 

I am stuck with the batch processing of audio signals with labels. I had a look into GUI in openSMILE but could not get the results as expected. 
<img width="739" alt="gui_problems" src="https://user-images.githubusercontent.com/13778028/45593958-46dc3300-b992-11e8-8156-935d529d5cd3.PNG">

My labels in csv file looked like this
<img width="110" alt="capture" src="https://user-images.githubusercontent.com/13778028/45593964-755a0e00-b992-11e8-8737-347936b23c79.PNG">

I included the following script in my config file `\{config/shared/arff_targets.conf.inc}`. Could you share your views of doing it the right way.

Thank you.

**Comment by saquibntt** [comment]
The batch processing is also done using a perl script in this toolkit. Didn't check that earlier.

**Comment by kudakwashez** [comment]
Did you get the solution for your problem. Im trying to extract my features too but nothing is being extracted. Its skipping all the files.

**Comment by saquibntt** [comment]
You should look into openSMILE documentation. They have provided the scripts named extract_features_batch.pl inside the scripts folder of openSMILE 2.3.
